web:
  image: chanezon/spring-doge
  ports:
   - 8080
  links: ["mongo"]
  environment:
   - MONGODB_URI=mongodb://mongo:27017/test
  labels:
   - "interlock.hostname=spring-doge"
   - "interlock.domain=chanezon.com"
mongo:
  image: mongo
